"""Signals stream — every signal generated by every strategy, approved or rejected."""
from __future__ import annotations

import streamlit as st
from streamlit_autorefresh import st_autorefresh

st.set_page_config(page_title="Signals — POLYBOT", page_icon="◇", layout="wide")

from polybot.dashboard.data_loader import (  # noqa: E402
    inject_styles,
    load_signals,
    render_sidebar,
    render_signal_card,
)

inject_styles()
st_autorefresh(interval=10_000, key="signals_refresh")
render_sidebar()

st.markdown('<div class="page-header">◇ SIGNALS</div>', unsafe_allow_html=True)

col1, col2, col3 = st.columns([1, 1, 1])
with col1:
    show = st.selectbox("Show", ["all", "approved only", "rejected only"], index=0)
with col2:
    strategy_filter = st.text_input("Filter by strategy", value="")
with col3:
    last_n = st.number_input("Show last N", min_value=10, max_value=500, value=100, step=10)

signals = load_signals(last_n=int(last_n))

if show == "approved only":
    signals = [s for s in signals if s.get("approved")]
elif show == "rejected only":
    signals = [s for s in signals if not s.get("approved")]

if strategy_filter.strip():
    needle = strategy_filter.strip().lower()
    signals = [s for s in signals if needle in (s.get("strategy") or "").lower()]

st.caption(f"Showing {len(signals)} signal(s)")

if not signals:
    st.info("No signals match the current filter.")
else:
    for sig in signals:
        render_signal_card(sig)
